const { app, BrowserWindow, ipcMain, shell, session } = require('electron');
const path   = require('path');
const { spawn, exec } = require('child_process');
const fs     = require('fs');
const os     = require('os');
const { autoUpdater } = require('electron-updater');
const { PostHog } = require('posthog-node');

let mainWindow;
let loginWindow = null;

// ── Analytics ─────────────────────────────────────────────────────────────────
const posthog = new PostHog('phc_TNjJDPmLHG5VEOsfD6x1xIKUgMP7dA2nmZnX9BCrG46', {
  host: 'https://us.i.posthog.com',
  flushAt: 1,
  flushInterval: 0,
});

// Use a stable anonymous ID stored in userData
const ANALYTICS_ID_FILE = path.join(app.getPath('userData'), 'analytics-id.txt');
function getAnalyticsId() {
  try {
    if (fs.existsSync(ANALYTICS_ID_FILE)) return fs.readFileSync(ANALYTICS_ID_FILE, 'utf8').trim();
    const id = 'user-' + Math.random().toString(36).substring(2) + Date.now().toString(36);
    fs.writeFileSync(ANALYTICS_ID_FILE, id);
    return id;
  } catch { return 'unknown'; }
}

function track(event, props = {}) {
  try {
    posthog.capture({ distinctId: getAnalyticsId(), event, properties: { ...props, app_version: app.getVersion() } });
  } catch {}
}

const OUTPUT_DIR    = path.join(os.homedir(), 'Music', 'Tuneplug');
const HOMEBREW_PATH = `/opt/homebrew/bin:/usr/local/bin:${process.env.PATH}`;
const COOKIE_FILE    = path.join(app.getPath('userData'), 'yt-cookies.txt');
const USER_FILE      = path.join(app.getPath('userData'), 'user-profile.json');

// ── Cookie helpers ────────────────────────────────────────────────────────────
function cookieFileExists() {
  try { return fs.existsSync(COOKIE_FILE) && fs.statSync(COOKIE_FILE).size > 100; }
  catch { return false; }
}

function getCookieArgs() {
  return cookieFileExists() ? ['--cookies', COOKIE_FILE] : [];
}

// Convert Electron cookies to Netscape format for yt-dlp
async function saveElectronCookies(sess) {
  const cookies = await sess.cookies.get({ domain: '.youtube.com' });
  const musicCookies = await sess.cookies.get({ domain: '.music.youtube.com' });
  const allCookies = [...cookies, ...musicCookies];

  if (!allCookies.length) return false;

  const lines = ['# Netscape HTTP Cookie File', '# Generated by Tuneplug', ''];
  for (const c of allCookies) {
    const domain     = c.domain.startsWith('.') ? c.domain : `.${c.domain}`;
    const subDomain  = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const secure     = c.secure ? 'TRUE' : 'FALSE';
    const expiry     = c.expirationDate ? Math.floor(c.expirationDate) : 0;
    lines.push(`${domain}\t${subDomain}\t${c.path || '/'}\t${secure}\t${expiry}\t${c.name}\t${c.value}`);
  }

  fs.writeFileSync(COOKIE_FILE, lines.join('\n'));
  return true;
}

// ── Binary detection ──────────────────────────────────────────────────────────
function findBinary(name) {
  for (const p of [
    `/opt/homebrew/bin/${name}`,
    `/usr/local/bin/${name}`,
    `/usr/bin/${name}`,
    path.join(app.getPath('userData'), 'bin', name),
  ]) { try { if (fs.existsSync(p)) return p; } catch {} }
  return name;
}

// ── Main window ───────────────────────────────────────────────────────────────
function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1160, height: 760, minWidth: 920, minHeight: 620,
    titleBarStyle: 'hiddenInset',
    backgroundColor: '#1c1c1e',
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });
  mainWindow.loadFile(path.join(__dirname, 'renderer', 'index.html'));
}

app.whenReady().then(() => {
  createWindow();
  app.on('activate', () => { if (BrowserWindow.getAllWindows().length === 0) createWindow(); });

  // Track app open
  track('app_opened');

  // Auto-updater — checks GitHub releases silently
  autoUpdater.autoDownload = true;
  autoUpdater.autoInstallOnAppQuit = true;
  autoUpdater.checkForUpdatesAndNotify().catch(() => {});

  autoUpdater.on('update-downloaded', () => {
    if (mainWindow) {
      mainWindow.webContents.send('update-ready');
    }
  });
});
app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); });

// ── Check deps ────────────────────────────────────────────────────────────────
ipcMain.handle('check-deps', async () => {
  const check = n => fs.existsSync(`/opt/homebrew/bin/${n}`);
  return { ytdlp: check('yt-dlp'), ffmpeg: check('ffmpeg') };
});

// ── Check login status ────────────────────────────────────────────────────────
ipcMain.handle('check-login', async () => {
  return { loggedIn: cookieFileExists() };
});

// ── Login: open YouTube Music in a popup window ───────────────────────────────
ipcMain.handle('login', async () => {
  return new Promise((resolve) => {
    if (loginWindow) { loginWindow.focus(); resolve({ success: false }); return; }

    // Use a separate session so cookies are isolated
    const loginSess = session.fromPartition('persist:youtube-login');

    loginWindow = new BrowserWindow({
      width: 500, height: 680,
      title: 'Sign in to YouTube Music',
      parent: mainWindow,
      modal: true,
      webPreferences: {
        session: loginSess,
        nodeIntegration: false,
        contextIsolation: true,
      },
    });

    loginWindow.loadURL('https://accounts.google.com/ServiceLogin?service=youtube&uilel=3&passive=true&continue=https%3A%2F%2Fmusic.youtube.com%2F');

    // Poll for successful login by checking for YouTube Music cookies
    const checkInterval = setInterval(async () => {
      try {
        const cookies = await loginSess.cookies.get({ name: 'SAPISID' });
        if (cookies.length > 0) {
          // Logged in — save cookies and close
          clearInterval(checkInterval);
          const saved = await saveElectronCookies(loginSess);
          if (saved) track('user_signed_in');
          loginWindow.close();
          resolve({ success: saved });
        }
      } catch {}
    }, 1000);

    loginWindow.on('closed', () => {
      clearInterval(checkInterval);
      loginWindow = null;
      resolve({ success: cookieFileExists() });
    });
  });
});

// ── Logout ────────────────────────────────────────────────────────────────────
ipcMain.handle('logout', async () => {
  try { fs.unlinkSync(COOKIE_FILE); } catch {}
  try { fs.unlinkSync(USER_FILE); } catch {}
  track('user_signed_out');
  return { success: true };
});

// ── Search songs ──────────────────────────────────────────────────────────────
ipcMain.handle('search-songs', async (_, query) => {
  track('search_performed', { type: 'songs', query });
  return new Promise((resolve, reject) => {
    const bin  = findBinary('yt-dlp');
    const proc = spawn(bin, [
      `ytsearch15:${query}`,
      '--flat-playlist', '--dump-json', '--no-warnings', '--quiet',
      ...getCookieArgs(),
    ], { env: { ...process.env, PATH: HOMEBREW_PATH } });

    let out = '';
    proc.stdout.on('data', d => { out += d.toString(); });
    proc.stderr.on('data', () => {});
    proc.on('close', () => {
      const results = out.trim().split('\n').filter(Boolean).flatMap(line => {
        try {
          const d = JSON.parse(line);
          if (!d.id) return [];
          return [{ type: 'song', id: d.id, title: d.title || '(untitled)',
            thumbnail: `https://i.ytimg.com/vi/${d.id}/mqdefault.jpg`,
            duration: d.duration || 0, channel: d.uploader || d.channel || '',
            views: d.view_count || 0 }];
        } catch { return []; }
      });
      resolve(results);
    });
    proc.on('error', () => reject(new Error('yt-dlp not found')));
  });
});

// ── Search playlists ──────────────────────────────────────────────────────────
ipcMain.handle('search-playlists', async (_, query) => {
  track('search_performed', { type: 'albums', query });
  return new Promise((resolve, reject) => {
    const bin = findBinary('yt-dlp');
    const cookieArgs = getCookieArgs();

    const doSearch = (url) => new Promise(res => {
      const proc = spawn(bin, [
        url, '--flat-playlist', '--dump-json', '--no-warnings', '--quiet',
        ...cookieArgs,
      ], { env: { ...process.env, PATH: HOMEBREW_PATH } });
      let out = '';
      proc.stdout.on('data', d => { out += d.toString(); });
      proc.stderr.on('data', () => {});
      proc.on('close', () => res(out));
      proc.on('error', () => res(''));
    });

    const browseReleases = (channelId) => new Promise(res => {
      const proc = spawn(bin, [
        `https://music.youtube.com/browse/${channelId}/releases`,
        '--flat-playlist', '--dump-json', '--no-warnings', '--quiet',
        ...cookieArgs,
      ], { env: { ...process.env, PATH: HOMEBREW_PATH } });
      let buf = '';
      proc.stdout.on('data', d => { buf += d.toString(); });
      proc.stderr.on('data', () => {});
      proc.on('close', () => {
        const ids = buf.trim().split('\n').filter(Boolean).flatMap(l => {
          try {
            const d = JSON.parse(l);
            const id = d.id || '';
            return (id.startsWith('OLAK5uy_') || id.startsWith('MPREb_')) ? [id] : [];
          } catch { return []; }
        });
        res([...new Set(ids)]);
      });
      proc.on('error', () => res([]));
    });

    const fetchAlbum = (id) => new Promise(res => {
      const url = id.startsWith('OLAK5uy_')
        ? `https://music.youtube.com/playlist?list=${id}`
        : `https://music.youtube.com/browse/${id}`;
      const proc = spawn(bin, [
        url, '--flat-playlist', '--dump-json', '--no-warnings', '--quiet',
        ...cookieArgs,
      ], { env: { ...process.env, PATH: HOMEBREW_PATH } });
      let buf = '';
      proc.stdout.on('data', d => { buf += d.toString(); });
      proc.stderr.on('data', () => {});
      proc.on('close', () => {
        try {
          const lines = buf.trim().split('\n').filter(Boolean);
          if (!lines.length) { res(null); return; }
          const first = JSON.parse(lines[0]);
          const trackCount = lines.filter(l => {
            try { const d = JSON.parse(l); return d.ie_key === 'Youtube' || (d.id && !d.id.startsWith('UC')); }
            catch { return false; }
          }).length || lines.length;
          const thumbs = first.thumbnails || [];
          const thumb  = thumbs.length
            ? thumbs[thumbs.length - 1].url
            : (first.id ? `https://i.ytimg.com/vi/${first.id}/mqdefault.jpg` : '');
          const rawTitle = first.playlist_title || first.playlist || '(untitled)';
          const title = rawTitle.replace(/^(Album|EP|Single)\s*-\s*/i, '').trim();
          res({ type: 'playlist', id, url, title, thumbnail: thumb,
            channel: first.playlist_uploader || first.playlist_channel || '',
            trackCount });
        } catch { res(null); }
      });
      proc.on('error', () => res(null));
    });

    (async () => {
      const [rawGeneral, rawAlbum] = await Promise.all([
        doSearch(`https://music.youtube.com/search?q=${encodeURIComponent(query)}`),
        doSearch(`https://music.youtube.com/search?q=${encodeURIComponent(query + ' album')}`),
      ]);

      const combined = rawGeneral + '\n' + rawAlbum;
      const mpreIds = [];
      for (const line of combined.trim().split('\n').filter(Boolean)) {
        try {
          const d = JSON.parse(line);
          const id = d.id || '';
          if (id.startsWith('MPREb_') && !mpreIds.includes(id)) mpreIds.push(id);
        } catch {}
      }

      let allIds = [];

      if (mpreIds.length) {
        const realChannelId = await new Promise(res => {
          const proc = spawn(bin, [
            `https://music.youtube.com/browse/${mpreIds[0]}`,
            '--flat-playlist', '--dump-json', '--no-warnings', '--quiet',
            '--playlist-items', '1',
            ...cookieArgs,
          ], { env: { ...process.env, PATH: HOMEBREW_PATH } });
          let buf = '';
          proc.stdout.on('data', d => { buf += d.toString(); });
          proc.stderr.on('data', () => {});
          proc.on('close', () => {
            try { res(JSON.parse(buf.trim().split('\n')[0]).channel_id || null); }
            catch { res(null); }
          });
          proc.on('error', () => res(null));
        });

        if (realChannelId) {
          const channelIds = await browseReleases(realChannelId);
          allIds = [...new Set([...mpreIds, ...channelIds])];
        } else {
          allIds = [...new Set(mpreIds)];
        }
      }

      if (!allIds.length) { resolve([]); return; }

      const results = [];
      const batchSize = 8;
      for (let i = 0; i < allIds.length; i += batchSize) {
        const batch = await Promise.all(allIds.slice(i, i + batchSize).map(fetchAlbum));
        results.push(...batch.filter(Boolean));
      }

      const stopWords = new Set(['the','a','an','and','or','of','in','on','by','ft','feat','with']);
      const artistWords = new Set(
        (results[0]?.channel || '').toLowerCase().split(/\s+/).filter(w => w.length > 1)
      );
      const allQueryWords = query.toLowerCase().split(/\s+/).filter(w => w.length > 1 && !stopWords.has(w));
      const albumWords    = allQueryWords.filter(w => !artistWords.has(w));
      const scoreWords    = albumWords.length ? albumWords : allQueryWords;

      const score = (album) => {
        const t = album.title.toLowerCase();
        const phrase = scoreWords.join(' ');
        if (phrase && t === phrase)       return 1000;
        if (phrase && t.includes(phrase)) return 500;
        return scoreWords.filter(w => t.includes(w)).length;
      };

      results.sort((a, b) => score(b) - score(a));
      resolve(results);
    })().catch(e => { console.error(e); reject(new Error('Search failed')); });
  });
});

// ── Fetch playlist tracks ─────────────────────────────────────────────────────
ipcMain.handle('fetch-playlist', async (_, url) => {
  return new Promise((resolve, reject) => {
    const bin  = findBinary('yt-dlp');
    const proc = spawn(bin, [
      url, '--flat-playlist', '--dump-json', '--no-warnings', '--quiet',
      ...getCookieArgs(),
    ], { env: { ...process.env, PATH: HOMEBREW_PATH } });

    let out = '';
    proc.stdout.on('data', d => { out += d.toString(); });
    proc.stderr.on('data', () => {});
    proc.on('close', code => {
      if (code !== 0 && !out.trim()) return reject(new Error('Could not fetch playlist.'));
      const lines  = out.trim().split('\n').filter(Boolean);
      const tracks = [];
      let plTitle = '', plThumb = '', channel = '', downloadUrl = url;
      for (const line of lines) {
        try {
          const d = JSON.parse(line);
          if (!plTitle) {
            plTitle  = d.playlist_title || d.playlist || d.title || 'Playlist';
            channel  = d.playlist_uploader || d.uploader || d.channel || '';
            const plId = d.playlist_id || '';
            if (plId.startsWith('OLAK5uy_')) {
              downloadUrl = `https://music.youtube.com/playlist?list=${plId}`;
            } else if (plId.startsWith('MPREb_')) {
              downloadUrl = `https://music.youtube.com/browse/${plId}`;
            }
          }
          const id = d.id || d.url?.split('v=')[1]?.split('&')[0];
          if (!id) continue;
          const thumb = `https://i.ytimg.com/vi/${id}/mqdefault.jpg`;
          if (!plThumb) plThumb = thumb;
          tracks.push({ id, title: d.title || '(untitled)', duration: d.duration || 0, thumbnail: thumb });
        } catch {}
      }
      if (!tracks.length) return reject(new Error('No tracks found.'));
      resolve({ title: plTitle, thumbnail: plThumb, channel, tracks, downloadUrl });
    });
    proc.on('error', () => reject(new Error('yt-dlp not found')));
  });
});

// ── Download single track ─────────────────────────────────────────────────────
const activeDownloads = new Map();

ipcMain.handle('download', async (_, videoId) => {
  return new Promise((resolve, reject) => {
    try { fs.mkdirSync(OUTPUT_DIR, { recursive: true }); } catch {}
    const bin = findBinary('yt-dlp');
    const proc = spawn(bin, [
      '-x', '--audio-format', 'mp3', '--audio-quality', '0',
      '--embed-thumbnail', '--add-metadata', '--convert-thumbnails', 'jpg',
      '--no-playlist', '--newline',
      '-o', path.join(OUTPUT_DIR, `${videoId}.%(ext)s`),
      `https://www.youtube.com/watch?v=${videoId}`,
    ], { env: { ...process.env, PATH: HOMEBREW_PATH } });

    activeDownloads.set(videoId, proc);
    const send = (percent, phase) => {
      mainWindow?.webContents.send('dl-progress', { videoId, percent, phase });
    };

    let buf = '';
    const onData = chunk => {
      buf += chunk.toString();
      const lines = buf.split('\n'); buf = lines.pop() || '';
      for (const line of lines) {
        const pct = line.match(/\[download\]\s+([\d.]+)%/);
        if (pct) { send(parseFloat(pct[1]) * 0.72, 'downloading'); continue; }
        if (line.includes('[ExtractAudio]'))   { send(78, 'converting'); continue; }
        if (line.includes('[EmbedThumbnail]')) { send(90, 'artwork');    continue; }
        if (line.includes('[Metadata]'))       { send(95, 'metadata');   continue; }
      }
    };
    proc.stdout.on('data', onData);
    proc.stderr.on('data', onData);

    proc.on('close', code => {
      activeDownloads.delete(videoId);
      if (code !== 0 && code !== null) return reject(new Error(`yt-dlp exited with code ${code}`));
      const mp3 = path.join(OUTPUT_DIR, `${videoId}.mp3`);
      if (!fs.existsSync(mp3)) return reject(new Error('MP3 not found'));
      send(97, 'adding');
      const scpt = path.join(os.tmpdir(), `tb_${Date.now()}.scpt`);
      fs.writeFileSync(scpt, `tell application "Music"\nadd POSIX file ${JSON.stringify(mp3)}\nend tell`);
      exec(`osascript "${scpt}"`, err => {
        try { fs.unlinkSync(scpt); } catch {}
        send(100, 'done');
        track('song_downloaded', { addedToMusic: !err });
        resolve({ success: true, addedToMusic: !err });
      });
    });
    proc.on('error', () => { activeDownloads.delete(videoId); reject(new Error('yt-dlp not found')); });
  });
});

// ── Download full playlist ────────────────────────────────────────────────────
ipcMain.handle('download-playlist', async (_, { url, title, trackCount }) => {
  return new Promise((resolve, reject) => {
    const safeName = title.replace(/[/\\:*?"<>|]/g, '-').trim() || 'Playlist';
    const albumDir = path.join(OUTPUT_DIR, safeName);
    try { fs.mkdirSync(albumDir, { recursive: true }); } catch {}

    const bin  = findBinary('yt-dlp');
    const proc = spawn(bin, [
      '-x', '--audio-format', 'mp3', '--audio-quality', '0',
      '--embed-thumbnail', '--add-metadata', '--convert-thumbnails', 'jpg',
      '--yes-playlist', '--newline',
      '--parse-metadata', 'playlist_title:%(album)s',
      '--parse-metadata', 'playlist_index:%(track_number)s',
      '-o', path.join(albumDir, '%(playlist_index)s - %(title)s.%(ext)s'),
      url,
    ], { env: { ...process.env, PATH: HOMEBREW_PATH } });

    activeDownloads.set(url, proc);
    const send = (percent, phase, trackIndex) => {
      mainWindow?.webContents.send('playlist-progress', { url, percent, phase, trackIndex });
    };

    let buf = '', currentTrack = 0;
    const onData = chunk => {
      buf += chunk.toString();
      const lines = buf.split('\n'); buf = lines.pop() || '';
      for (const line of lines) {
        const tm = line.match(/\[download\] Downloading item (\d+) of \d+/);
        if (tm) { currentTrack = parseInt(tm[1]); send(((currentTrack-1)/trackCount)*85, 'downloading', currentTrack); continue; }
        const pm = line.match(/\[download\]\s+([\d.]+)%/);
        if (pm) { send((((currentTrack-1)+parseFloat(pm[1])/100)/trackCount)*85, 'downloading', currentTrack); continue; }
        if (line.includes('[ExtractAudio]'))   { send(((currentTrack-0.3)/trackCount)*85, 'converting', currentTrack); continue; }
        if (line.includes('[EmbedThumbnail]')) { send(((currentTrack-0.1)/trackCount)*85, 'artwork',    currentTrack); continue; }
      }
    };
    proc.stdout.on('data', onData);
    proc.stderr.on('data', onData);

    proc.on('close', code => {
      activeDownloads.delete(url);
      console.log('[DEBUG] yt-dlp exited with code:', code);
      console.log('[DEBUG] albumDir:', albumDir);
      console.log('[DEBUG] albumDir exists:', fs.existsSync(albumDir));
      try { console.log('[DEBUG] albumDir contents:', fs.readdirSync(albumDir)); } catch(e) { console.log('[DEBUG] readdirSync error:', e.message); }
      send(90, 'adding', trackCount);
      let mp3s = [];
      // Search albumDir and one level of subdirectories for MP3s
      try {
        const topLevel = fs.readdirSync(albumDir).filter(f => f.toLowerCase().endsWith('.mp3')).map(f => path.join(albumDir, f));
        const subLevel = fs.readdirSync(albumDir).flatMap(f => {
          try {
            const sub = path.join(albumDir, f);
            if (fs.statSync(sub).isDirectory()) {
              return fs.readdirSync(sub).filter(sf => sf.toLowerCase().endsWith('.mp3')).map(sf => path.join(sub, sf));
            }
          } catch {}
          return [];
        });
        mp3s = [...topLevel, ...subLevel].sort();
      } catch {}
      if (!mp3s.length) return reject(new Error(`Download failed — no tracks saved (code ${code})`));
      const scpt = path.join(os.tmpdir(), `tb_pl_${Date.now()}.scpt`);
      fs.writeFileSync(scpt, `tell application "Music"\n${mp3s.map(p => `add POSIX file ${JSON.stringify(p)}`).join('\n')}\nend tell`);
      exec(`osascript "${scpt}"`, err => {
        try { fs.unlinkSync(scpt); } catch {}
        send(100, 'done', trackCount);
        track('album_downloaded', { trackCount: mp3s.length, addedToMusic: !err, albumTitle: title });
        resolve({ success: true, trackCount: mp3s.length, addedToMusic: !err });
      });
    });
    proc.on('error', () => { activeDownloads.delete(url); reject(new Error('yt-dlp not found')); });
  });
});

ipcMain.handle('install-update', () => { autoUpdater.quitAndInstall(); });

ipcMain.handle('cancel-download', (_, id) => {
  const p = activeDownloads.get(id);
  if (p) { p.kill('SIGTERM'); activeDownloads.delete(id); }
});

ipcMain.handle('open-folder', () => shell.openPath(OUTPUT_DIR));

app.on('before-quit', () => { try { posthog.shutdown(); } catch {} });
